apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-slice-admin
rules:
- apiGroups: [ "config.apps.tanzu.vmware.com" ]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-slice-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-slice-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: app-pre